version: '2'
services:
  frontend:
    build: frontend
    restart: always
    ports:
      - "0.0.0.0:43080:80"
    volumes:
      - $PWD/frontend/html:/usr/share/nginx/html
  api:
    build: backend
    restart: always
    ports:
      - '127.0.0.1:5000:5000'
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - SENTRY_DSN=$SENTRY_DSN
    volumes:
      - $PWD/backend/map.json:/app/map.json
      - $PWD/backend/utils.py:/app/utils.py
      - $PWD/backend/main.py:/app/main.py