version: '2'
services:
  frontend:
    build: frontend
    restart: always
    ports:
      - "0.0.0.0:43080:80"
  api:
    build: backend
    restart: always
    environment:
      - SENTRY_DSN=$SENTRY_DSN